# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

package(default_visibility = ["//visibility:public"])

constraint_setting(name = "jetpack")

constraint_value(
    name = "4.5",
    constraint_setting = ":jetpack",
)

constraint_value(
    name = "4.6",
    constraint_setting = ":jetpack",
)

constraint_value(
    name = "6.1",
    constraint_setting = ":jetpack",
)