package(default_visibility = ["//visibility:public"])

constraint_setting(name = "jetpack")

constraint_value(
    name = "4.5",
    constraint_setting = ":jetpack",
)

constraint_value(
    name = "4.6",
    constraint_setting = ":jetpack",
)
