# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "jit_models",
    srcs = glob(["**/*.jit.pt"]),
)
