"component: api [C++]":
  - "narendasan"

"component: api [Python]":
  - "gs-olive"
  - "peri044"

"component: api":
  - "narendasan"

"component: build system":
  - "narendasan"

"component: conversion":
  - "apbose"
  - "peri044"

"component: converters":
  - "apbose"
  - "zewenli98"

"component: core":
  - "narendasan"
  - "peri044"
  - "bowang007"

"component: dynamo":
  - "narendasan"
  - "gs-olive"
  - "peri044"

"component: evaluators":
  - "narendasan"
  - "peri044"

"component: execution":
  - "narendasan"

"component: lowering":
  - "peri044"
  - "gs-olive"

"component: partitioning":
  - "bowang007"
  - "peri044"

"component: plugins":
  - "peri044"

"component: quantization":
  - "peri044"
  - "bowang007"

"component: runtime":
  - "narendasan"

"component: tests":
  - "narendasan"

"component: torch_compile":
  - "gs-olive"
  - "narendasan"

"component: torchtrtc":
  - "narendasan"

"component: dependencies":
  # Work RE: upgrading dependencies in the compiler / testing new versions
  - "peri044"
  - "bowang007"
  - "narendasan"

"documentation":
  - "narendasan"

"examples":
  # Sample applications and notebooks on how to use TorchTRT features
  - "peri044"
  - "tanayvarshney"

"infrastructre":
  - "narendasan"

"component: packaging":
  - "narendasan"
  - "peri044"

"channel: NGC":
  - "peri044"

"channel: linux-x86":
  - "narendasan"
  - "peri044"

"channel: linux-sbsa":
  - "bowang007"

"channel: windows":
  - "narendasan"

"channel: linux-jetpack":
  - "narendasan"
  - "bowang007"

"component: tooling":
    - "narendasan"

"backend: tensorrt":
    - "zewenli98"

"backend: tensorrt-rtx":
    - "lanluo-nvidia"

"performance":
  - "peri044"
  - "bowang007"

"channel: docker":
  - "narendasan"

"ux":
  # Issues related to the user experience including debugging and installation
  - "narendasan"
  - "peri044"

"component: fx":
  - "frank-wei"
  - "yinghai"
  - "wushirong"
