"component: torchtrtc":
    - cpp/torchtrtc/**/*

"component: api [C++]":
    - cpp/**/*

"component: api [Python]":
    - py/**/*

"component: core":
    - core/**/*
    - py/torch_tensorrt/dynamo/**/*

"component: conversion":
    - core/conversion/**/*
    - py/torch_tensorrt/dynamo/conversion/**/*

"component: converters":
    - core/conversion/converters/**/*
    - py/torch_tensorrt/dynamo/conversion/impl/**/*

"component: evaluators":
    - core/conversion/evaluators/**/*

"component: fx":
    - py/torch_tensorrt/fx/**/*

"component: dynamo":
    - py/torch_tensorrt/dynamo/**/*

"component: torch_compile":
    - py/torch_tensorrt/dynamo/backend/*

"component: partitioning":
    - core/partitioning/**/*

"component: runtime":
    - core/runtime/**/*
    - py/torch_tensorrt/dynamo/runtime/**/*

"component: lowering":
    - core/lowering/**/*
    - py/torch_tensorrt/dynamo/lowering/**/*

"component: tests":
    - tests/**/*

"component: build system":
    - MODULE.bazel
    - BUILD
    - pyproject.toml
    - setup.py
    - toolchain/**/*

"documentation":
    - docs/**/*
    - docsrc/**/*
