"component: torchtrtc":
  - changed-files:
      - any-glob-to-any-file:
          - cpp/torchtrtc/**/*

"component: api [C++]":
  - changed-files:
      - any-glob-to-any-file:
          - cpp/**/*

"component: api [Python]":
  - changed-files:
      - any-glob-to-any-file:
          - py/**/*

"component: core":
  - changed-files:
      - any-glob-to-any-file:
          - core/**/*
          - py/torch_tensorrt/dynamo/**/*

"component: conversion":
  - changed-files:
      - any-glob-to-any-file:
          - core/conversion/**/*
          - py/torch_tensorrt/dynamo/conversion/**/*

"component: converters":
  - changed-files:
      - any-glob-to-any-file:
          - core/conversion/converters/**/*
          - py/torch_tensorrt/dynamo/conversion/impl/**/*

"component: evaluators":
  - changed-files:
      - any-glob-to-any-file:
          - core/conversion/evaluators/**/*

"component: fx":
  - changed-files:
      - any-glob-to-any-file:
          - py/torch_tensorrt/fx/**/*

"component: dynamo":
  - changed-files:
      - any-glob-to-any-file:
          - py/torch_tensorrt/dynamo/**/*

"component: torch_compile":
  - changed-files:
      - any-glob-to-any-file:
          - py/torch_tensorrt/dynamo/backend/*

"component: partitioning":
  - changed-files:
      - any-glob-to-any-file:
          - core/partitioning/**/*

"component: runtime":
  - changed-files:
      - any-glob-to-any-file:
          - core/runtime/**/*
          - py/torch_tensorrt/dynamo/runtime/**/*

"component: lowering":
  - changed-files:
      - any-glob-to-any-file:
          - core/lowering/**/*
          - py/torch_tensorrt/dynamo/lowering/**/*

"component: tests":
  - changed-files:
      - any-glob-to-any-file:
          - tests/**/*

"component: build system":
  - changed-files:
      - any-glob-to-any-file:
          - MODULE.bazel
          - BUILD
          - pyproject.toml
          - setup.py
          - toolchain/**/*

"documentation":
  - changed-files:
      - any-glob-to-any-file:
          - docs/**/*
          - docsrc/**/*
