package(default_visibility = ["//visibility:public"])

platform(
    name = "aarch64_linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
    ],
)

platform(
    name = "jetpack_4.5",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
        "@//toolchains/jetpack:4.5",
    ],
)

platform(
    name = "jetpack_4.6",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
        "@//toolchains/jetpack:4.6",
    ],
)

platform(
    name = "jetpack_5.0",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
        "@//toolchains/jetpack:4.6",
    ],
)

platform(
    name = "ci_rhel_x86_64_linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
        "@//toolchains/distro:ci_rhel",
    ],
)
