package(default_visibility = ["//visibility:public"])

platform(
    name = "aarch64_linux",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
    ],
)

platform(
    name = "jetpack_4.5",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
        "@//toolchains/jetpack:4.5"
    ]
)

platform(
    name = "jetpack_4.6",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:aarch64",
        "@//toolchains/jetpack:4.6"
    ]
)
