# buildifier: disable=module-docstring
"""
Repository rule and helper macro to detect whether the libtorch dep was built
with USE_C10D_NCCL=True by inspecting installed headers inside @libtorch.

Usage in WORKSPACE (must come after the @libtorch new_local_repository):
    load("//toolchains/torch_nccl:defs.bzl", "torch_nccl_detect")
    torch_nccl_detect(name = "torch_nccl")

Usage in BUILD files:
    load("//toolchains/torch_nccl:defs.bzl", "if_torch_nccl")

    cc_binary(
        name = "my_target",
        copts = if_torch_nccl(["-DUSE_C10D_NCCL"]),
        deps  = if_torch_nccl(["//core:nccl_backend"]),
    )
"""

_BUILD_TEMPLATE = """\
# AUTO-GENERATED by //toolchains/torch_nccl:defs.bzl – do not edit.
# Detected USE_C10D_NCCL={detected} via {source}
load("@bazel_skylib//rules:common_settings.bzl", "bool_flag")

package(default_visibility = ["//visibility:public"])

# Reflects whether @libtorch was compiled with USE_C10D_NCCL=True.
# Can be overridden on the command line:
#   --@torch_nccl//:nccl_enabled=true
#   --@torch_nccl//:nccl_enabled=false
bool_flag(
    name = "nccl_enabled",
    build_setting_default = {default},
)

config_setting(
    name = "with_nccl",
    flag_values = {{":nccl_enabled": "true"}},
)

config_setting(
    name = "without_nccl",
    flag_values = {{":nccl_enabled": "false"}},
)
"""

def _torch_nccl_detect_impl(rctx):
    # Resolve the libtorch workspace root.  new_local_repository creates the
    # workspace at the path= arg, so dirname of any BUILD label within it is
    # that same root.
    libtorch_root = rctx.path(Label("@libtorch//:BUILD")).dirname

    has_nccl = False
    source = "unknown"

    # NCCL is only supported on Linux (PyTorch's cmake/Dependencies.cmake
    # unconditionally sets USE_NCCL=OFF on non-Linux).  Short-circuit here so
    # we never attempt .so scanning or grep on macOS/Windows hosts.
    if rctx.os.name != "linux":
        source = "non-linux host ({}) — NCCL unsupported".format(rctx.os.name)
        rctx.file(
            "BUILD.bazel",
            _BUILD_TEMPLATE.format(detected = False, source = source, default = "False"),
        )
        return

    # -------------------------------------------------------------------------
    # Strategy: grep for "ProcessGroupNCCL" in compiled shared libraries.
    #
    # ProcessGroupNCCL is compiled into the CUDA/HIP library only when
    # USE_C10D_NCCL=ON (requires both USE_DISTRIBUTED and USE_NCCL per
    # pytorch/CMakeLists.txt:
    #   cmake_dependent_option(USE_C10D_NCCL ... ON "USE_DISTRIBUTED;USE_NCCL" OFF)
    # ).  The string appears nowhere in a USE_C10D_NCCL=OFF build.
    #
    # We prefer smaller libraries for speed (grep -q exits on first match):
    #   1. lib/libtorch_python.so  (~27 MB, pip builds only — skipped in cmake
    #      standalone libtorch because torch/CMakeLists.txt returns early when
    #      BUILD_PYTHON=OFF)
    #   2. lib/libtorch_cuda.so    (~1 GB, present in all CUDA builds)
    #   3. lib/libtorch_hip.so     (ROCm equivalent)
    #
    # Notes on what does NOT work:
    #  - ATen/Config.h: no NCCL symbol exists there at all.
    #  - ProcessGroupNCCL.hpp existence: always installed via unconditional glob.
    #  - ProcessGroupNCCL.hpp content: identical regardless of build flags;
    #    the #ifdef guards are for downstream consumers, not build artifacts.
    #  - caffe2/core/macros.h {"USE_NCCL","1"}: records USE_NCCL only;
    #    a build with USE_DISTRIBUTED=OFF would be a false positive.
    #  - TorchConfig.cmake: pip wheels do not contain TORCH_USE_C10D_NCCL.
    # -------------------------------------------------------------------------
    candidates = [
        ("lib/libtorch_python.so", "lib/libtorch_python.so"),
        ("lib/libtorch_cuda.so", "lib/libtorch_cuda.so"),
        ("lib/libtorch_hip.so", "lib/libtorch_hip.so"),
    ]

    found_so = False
    for (rel_path, label) in candidates:
        so = libtorch_root.get_child(rel_path)
        if so.exists:
            result = rctx.execute(["grep", "-q", "ProcessGroupNCCL", str(so)])
            has_nccl = result.return_code == 0
            source = label
            found_so = True
            break

    if not found_so:
        # buildifier: disable=print
        print(
            "WARNING: torch_nccl_detect: could not find libtorch_python.so, " +
            "libtorch_cuda.so, or libtorch_hip.so under @libtorch root " +
            str(libtorch_root) + ". Defaulting nccl_enabled=False.",
        )
        source = "no .so found (defaulting to False)"

    rctx.file(
        "BUILD.bazel",
        _BUILD_TEMPLATE.format(
            detected = has_nccl,
            source = source,
            default = "True" if has_nccl else "False",
        ),
    )

torch_nccl_detect = repository_rule(
    implementation = _torch_nccl_detect_impl,
    # Re-run whenever the libtorch installation changes.
    configure = True,
    doc = """\
Detects whether the @libtorch dep was compiled with USE_C10D_NCCL=True
(which requires both USE_DISTRIBUTED and USE_NCCL).  Greps for the string
"ProcessGroupNCCL" in the compiled shared libraries (libtorch_python.so,
libtorch_cuda.so, or libtorch_hip.so) — the only reliable artifact that
differs between ON/OFF builds.  Short-circuits to False on non-Linux hosts
since PyTorch unconditionally disables NCCL outside Linux.
Note: no header file can signal USE_C10D_NCCL — ATen/Config.h has no NCCL
symbol; ProcessGroupNCCL.hpp is always installed unconditionally;
caffe2/core/macros.h only records USE_NCCL (not USE_C10D_NCCL);
TorchConfig.cmake.in never writes a TORCH_USE_C10D_NCCL variable.
Exposes the result as @torch_nccl//:with_nccl / :without_nccl config_settings.
""",
)

# ---------------------------------------------------------------------------
# Helper macro
# ---------------------------------------------------------------------------

def if_torch_nccl(nccl, no_nccl = []):
    """select() wrapper for NCCL-conditional values.

    Args:
        nccl:     Value when @torch_nccl//:with_nccl matches.
        no_nccl:  Value otherwise (default: []).
    """
    return select({
        "@torch_nccl//:with_nccl": nccl,
        "//conditions:default": no_nccl,
    })
