"""Torch-TensorRT test-suite manifest + runner (the Layer-0 "brain").

This package is the single source of truth for *what each CI/local test job runs*.
It replaces the ``trt_tier_*`` bash functions in ``tests/py/utils/ci_helpers.sh``.

  * ``suites.py``   — the manifest: ``SUITES = [Suite(...), ...]`` (pure data).
  * ``runner.py``   — the one engine that turns a ``Suite`` into a ``pytest`` command.
  * ``__main__.py`` — the CLI: ``python -m tests.ci {list,show,run,matrix}``.

Both ``just`` (local) and CI call ``python -m tests.ci run <suite>``; CI's job
matrix is generated by ``python -m tests.ci matrix``. There is nothing to drift.
"""

from .suites import SUITES, Lane, Suite, Tier, Variant

__all__ = ["SUITES", "Suite", "Lane", "Tier", "Variant"]
