# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

load(":defs.bzl", "dep_collection")

package(default_visibility = ["//visibility:public"])

dep_collection(
    name = "compute_libs",
    build_setting_default = "default",
)
