FROM nvcr.io/nvidia/pytorch:21.06-py3 as builder

RUN apt-get update && apt-get install -y curl gnupg  && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
RUN mv bazel.gpg /etc/apt/trusted.gpg.d/
RUN echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list

RUN apt-get update && apt-get install -y bazel-4.0.0 && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/bazel-4.0.0 /usr/bin/bazel
# Workaround for bazel expecting both static and shared versions, we only use shared libraries inside container
RUN cp /usr/lib/x86_64-linux-gnu/libnvinfer.so /usr/lib/x86_64-linux-gnu/libnvinfer_static.a

RUN pip install notebook

FROM builder as trtorch

COPY . /opt/trtorch/src
WORKDIR /opt/trtorch/src
RUN cp ./docker/WORKSPACE.cu.docker  WORKSPACE

RUN bazel build //:libtrtorch //cpp/trtorchc:trtorchc //cpp/trtorchexec:trtorchexec --compilation_mode opt

WORKDIR /opt/trtorch/src/py

RUN pip install ipywidgets --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org
RUN jupyter nbextension enable --py widgetsnbextension

# Locale is not set by default
RUN apt-get update && apt-get install -y locales ninja-build && rm -rf /var/lib/apt/lists/* && locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN MAX_JOBS=1 python3 setup.py install --use-cxx11-abi

RUN conda init bash

WORKDIR /opt/trtorch/src
RUN mkdir -p /opt/trtorch/lib /opt/trtorch/bin
RUN cp ./bazel-bin/cpp/trtorchc/trtorchc /opt/trtorch/bin
RUN cp ./bazel-bin/cpp/trtorchexec/trtorchexec /opt/trtorch/bin
RUN cp ./bazel-bin/cpp/api/lib/libtrtorch.so /opt/trtorch/lib
RUN cp ./bazel-bin/cpp/api/lib/libtrtorchrt.so /opt/trtorch/lib
RUN cp ./bazel-bin/cpp/api/lib/libtrtorch_plugins.so /opt/trtorch/lib
# RUN cp /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_global_deps.so /opt/trtorch/lib

ENV LD_LIBRARY_PATH /opt/conda/lib/python3.8/site-packages/torch/lib:/opt/trtorch/lib:${LD_LIBRARY_PATH}
ENV PATH /opt/trtorch/bin:${PATH}

WORKDIR /opt/trtorch/
CMD /bin/bash
