FROM nvcr.io/nvidia/pytorch:20.07-py3

RUN apt-get update && apt-get install curl gnupg  && rm -rf /var/lib/apt/lists/*

RUN curl https://bazel.build/bazel-release.pub.gpg | apt-key add - && \
    echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list

RUN apt-get update && apt-get install bazel-3.4.1 && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/bazel-3.4.1 /usr/bin/bazel

RUN pip install notebook

COPY . /workspace/TRTorch
RUN rm /workspace/TRTorch/WORKSPACE
COPY ./docker/WORKSPACE.cu11.docker  /workspace/TRTorch/WORKSPACE

# Workaround for bazel expecting both static and shared versions, we only use shared libraries inside container
RUN cp /usr/lib/x86_64-linux-gnu/libnvinfer.so /usr/lib/x86_64-linux-gnu/libnvinfer_static.a

WORKDIR /workspace/TRTorch
RUN bazel build //:libtrtorch --compilation_mode opt

WORKDIR /workspace/TRTorch/py

# Locale is not set by default
RUN apt-get update && apt-get install -y locales ninja-build && rm -rf /var/lib/apt/lists/* && locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
RUN python3 setup.py install --use-cxx11-abi

RUN conda init bash

WORKDIR /workspace/TRTorch/notebooks