FROM nvcr.io/nvidia/pytorch:20.07-py3

RUN echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list \
  && curl https://bazel.build/bazel-release.pub.gpg | apt-key add -

RUN apt-get update && apt-get install bazel-3.3.1 && rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/bazel-3.3.1 /usr/bin/bazel

