package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "supportedops",
    srcs = [
        "main.cpp"
    ],
    deps = [
        "//cpp/api:trtorch",
        "//core/conversion/converters"
    ],
)
