package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "libtrtorch.so",
    srcs = [],
    linkshared = True,
    linkstatic = True,
    deps = [
        "//cpp/api:trtorch",
    ],
)
