# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

test_suite(
    name = "conversion_tests",
    tests = [
        "//tests/core/conversion/converters:converter_tests",
        "//tests/core/conversion/evaluators:evaluator_tests",
    ],
)
