package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "supportedops",
    srcs = [
        "main.cpp",
    ],
    deps = [
        "//core/conversion/converters",
        "//cpp/api:trtorch",
    ],
)
