# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

load(":defs.bzl", "dep_src")

package(default_visibility = ["//visibility:public"])

dep_src(
    name = "torch",
    build_setting_default = "archive",
)
