# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

package(default_visibility = ["//visibility:public"])

constraint_setting(name = "distro")

constraint_value(
    name = "ci_rhel",
    constraint_setting = ":distro",
)
