name: Lan test workflow main

on:
  pull_request:
  push:
    branches:
      - main
      - nightly
      - release/*
    tags:
      # NOTE: Binary build pipelines should only get triggered on release candidate builds
      # Release candidate tags look like: v1.11.0-rc1
      - v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  trigger-fail-fast-test:
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/build-test-linux-x86_64.yml
    with:
      fail-fast: true

  trigger-linux-test:
    needs: [fail-fast-test]
    strategy:
      fail-fast: false
    if: always()
    name: build-test on linux-x86_64
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/build-test-linux-x86_64.yml

  trigger-windows-test:
    needs: [trigger-fail-fast-test]
    if: always()
    name: build-test on windows
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/build-test-windows.yml

  wait-all-jobs:
    needs: [trigger-linux-test, trigger-windows-test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Wait for all jobs to complete
        run: |
          echo "Waiting for all jobs to complete..."

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ inputs.repository }}-${{ github.event_name == 'workflow_dispatch' }}-${{ inputs.job-name }}
  cancel-in-progress: false