name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has not seen activity for 30 days, Remove stale label or comment or this will be closed in 5 days'
        stale-pr-message: 'This PR has not seen activity for 30 days, Remove stale label or comment or this will be closed in 5 days'
        stale-issue-label: 'No Activity'
        exempt-issue-labels: 'WIP'
        stale-pr-label: 'No Activity'
        exempt-pr-labels: 'WIP'
        days-before-stale: 30
        days-before-close: 5
